[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
skinvault = "44UwMzMZUcobRp4YyucjvAbBeTFJ3uBPxg7YqwHS2ncp"

[programs.testnet]
skinvault = "44UwMzMZUcobRp4YyucjvAbBeTFJ3uBPxg7YqwHS2ncp"

[programs.localnet]
skinvault = "44UwMzMZUcobRp4YyucjvAbBeTFJ3uBPxg7YqwHS2ncp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./node_modules/.bin/mocha -t 300000 tests/integration-flow.test.ts"
test-integration = "./node_modules/.bin/mocha -t 300000 tests/integration-flow.test.ts"
test-mainnet = "./node_modules/.bin/mocha -t 300000 tests/vrf-mainnet.test.ts"
test-simple = "./node_modules/.bin/mocha -t 300000 tests/vrf-simple.test.ts"
test-vrf-security = "./node_modules/.bin/mocha -t 300000 tests/vrf-security.test.ts"
