[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
skinvault = "6cSLcQ5RCyzPKeFWux2UMjm3SWf3tD41vHK5qsuphzKZ"

[programs.localnet]
skinvault = "6cSLcQ5RCyzPKeFWux2UMjm3SWf3tD41vHK5qsuphzKZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./node_modules/.bin/mocha -t 300000 tests/integration-flow.test.ts"
test-candy-machine = "./node_modules/.bin/mocha -t 300000 tests/candy-machine.test.ts"
test-mainnet = "./node_modules/.bin/mocha -t 300000 tests/vrf-mainnet.test.ts"
test-simple = "./node_modules/.bin/mocha -t 300000 tests/vrf-simple.test.ts"
test-vrf-security = "./node_modules/.bin/mocha -t 300000 tests/vrf-security.test.ts"

[test]
startup_wait = 5000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
