[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
skinvault = "HkgLfcBuBwxJroAk2C874rWjp7FzkThAXBGwcoWWRPH1"

[programs.localnet]
skinvault = "HkgLfcBuBwxJroAk2C874rWjp7FzkThAXBGwcoWWRPH1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "./node_modules/.bin/mocha -t 300000 tests/candy-machine.test.ts"
test-integration = "./node_modules/.bin/mocha -t 300000 tests/integration-flow.test.ts"
test-mainnet = "./node_modules/.bin/mocha -t 300000 tests/vrf-mainnet.test.ts"
test-simple = "./node_modules/.bin/mocha -t 300000 tests/vrf-simple.test.ts"
test-vrf-security = "./node_modules/.bin/mocha -t 300000 tests/vrf-security.test.ts"
