[toolchain]
anchor_version = "0.31.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
skinvault = "7QqkF39AGbTDP88NFHPDVfBQWxFL8mNSUZh6J2cy5HWA"

[programs.devnet]
skinvault = "FuXM6BsXE54CAXaJLYRL91io2bgUMBFMWVDxTHkbaP9F"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
types = "types"
