[toolchain]
anchor_version = "0.31.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
skinvault = "7QqkF39AGbTDP88NFHPDVfBQWxFL8mNSUZh6J2cy5HWA"

[programs.devnet]
skinvault = "FuXM6BsXE54CAXaJLYRL91io2bgUMBFMWVDxTHkbaP9F"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
types = "types"

[scripts]
test = "./node_modules/.bin/mocha -t 300000 tests/vrf-security.test.ts"
test-simple = "./node_modules/.bin/mocha -t 300000 tests/vrf-simple.test.ts"
test-mainnet = "./node_modules/.bin/mocha -t 300000 tests/vrf-mainnet.test.ts"